version: 1.1.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- cmd: choco install imagemagick -y --no-progress
- cmd: refreshenv && "%ProgramFiles%\ImageMagick-7.1.2-Q16-HDRI\magick.exe" src\PlayerOne.Windows\Assets\player-one-icon.webp -define icon:auto-resize=256,128,64,48,32,16 src\PlayerOne.Windows\Assets\player-one.ico
- cmd: dotnet restore PlayerOne.Windows.sln
- cmd: dotnet build PlayerOne.Windows.sln -c Release --no-restore
- cmd: dotnet publish src\PlayerOne.Windows\PlayerOne.Windows.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:DebugType=None -o artifacts\publish
after_build:
- cmd: 7z a -tzip artifacts\Player-One-Windows-Portable.zip .\artifacts\publish\*
- cmd: choco install innosetup -y --no-progress
- cmd: iscc installer\PlayerOne.iss
- cmd: 7z a -tzip artifacts\Player-One-Windows-Setup.zip .\artifacts\installer\Player-One-Setup.exe
artifacts:
- path: artifacts\Player-One-Windows-Portable.zip
  name: Player-One-Windows-Portable
- path: artifacts\Player-One-Windows-Setup.zip
  name: Player-One-Windows-Setup