using System.Text.Json;using PlayerOne.Windows.Models;using PlayerOne.Windows.Services;namespace PlayerOne.Windows;
public partial class CatalogWindow:System.Windows.Window{readonly DeviceAuth auth;readonly string kind;readonly PlayerOneApi api=new();List<XtreamItem> all=[];string? host,user,pass;public CatalogWindow(DeviceAuth a,string k){InitializeComponent();auth=a;kind=k;TitleText.Text=k=="live"?"LIVE":k=="movie"?"MOVIES":"SERIES";Loaded+=async(_,__)=>await LoadAsync();}
async Task LoadAsync(){try{using var d=await api.GetPlaylistsAsync(auth);if(!d.RootElement.TryGetProperty("playlists",out var arr)||arr.ValueKind!=JsonValueKind.Array||arr.GetArrayLength()==0){MessageBox.Show("No playlists linked to this device.","Player One");return;}var selected=PlaylistSelectionStore.Load();JsonElement p=arr[0];foreach(var x in arr.EnumerateArray())if(x.TryGetProperty("id",out var xid)&&selected==xid.GetInt64()){p=x;break;}var id=p.GetProperty("id").GetInt64();PlaylistSelectionStore.Save(id);using var cfg=await api.GetPlaylistConfigAsync(auth,id);var q=cfg.RootElement.GetProperty("playlist");var type=q.TryGetProperty("type",out var t)?t.ToString().ToLowerInvariant():"";if(type=="xtream"){host=q.GetProperty("host").ToString();user=q.GetProperty("username").ToString();pass=q.GetProperty("password").ToString();all=await new XtreamClient().LoadAsync(host,user,pass,kind);}else if(type=="m3u"&&q.TryGetProperty("url",out var u))all=await new M3uClient().LoadAsync(u.ToString(),kind);Bind();}catch(Exception ex){MessageBox.Show(ex.Message,"Player One");}}
void Bind(){var gs=all.Select(x=>x.Group).Where(x=>!string.IsNullOrWhiteSpace(x)).Distinct(StringComparer.OrdinalIgnoreCase).ToList();Groups.ItemsSource=kind=="live"?new[]{"Favorites"}.Concat(gs).Concat(new[]{"All"}):new[]{"Recently added","Continue watching","Favorites"}.Concat(gs).Concat(new[]{"All"});Groups.SelectedIndex=0;Filter();}
void Filter(){var g=Groups.SelectedItem?.ToString();var s=SearchBox.Text.Trim();IEnumerable<XtreamItem> src=all;if(s.Length>0)src=all.Where(x=>x.Name.Contains(s,StringComparison.OrdinalIgnoreCase)||x.Group.Contains(s,StringComparison.OrdinalIgnoreCase));else if(g=="Favorites"){var f=PlayerStateStore.Favorites(auth,PlaylistSelectionStore.Load()).Where(x=>x.Type==kind||kind=="live"&&x.Type=="live").ToList();src=all.Where(x=>f.Any(v=>v.Id==x.Id||(!string.IsNullOrWhiteSpace(v.StreamUrl)&&v.StreamUrl==x.StreamUrl)));}else if(g=="Continue watching"){var r=PlayerStateStore.Recents(auth,PlaylistSelectionStore.Load()).Where(PlayerStateStore.Meaningful).ToList();src=all.Where(x=>r.Any(v=>(!string.IsNullOrWhiteSpace(v.StreamUrl)&&v.StreamUrl==x.StreamUrl)||Norm(v.Title)==Norm(x.Name)));}else if(g=="Recently added")src=all.Any(x=>x.AddedAt>0)?all.OrderByDescending(x=>x.AddedAt).Take(30):all.Take(30);else if(g!="All"&&!string.IsNullOrEmpty(g))src=all.Where(x=>x.Group==g);Items.ItemsSource=src.ToList();}
static string Norm(string? v)=>new string((v??"").Where(char.IsLetterOrDigit).Select(char.ToLowerInvariant).ToArray());
void Group_Changed(object s,System.Windows.Controls.SelectionChangedEventArgs e)=>Filter();void Search_Changed(object s,System.Windows.Controls.TextChangedEventArgs e)=>Filter();void Back_Click(object s,System.Windows.RoutedEventArgs e)=>Close();void Window_KeyDown(object s,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Escape){Close();e.Handled=true;}}
void ToggleFavorite(XtreamItem x){PlayerStateStore.ToggleFavorite(auth,PlaylistSelectionStore.Load(),new(x.Kind,x.Id,x.Name,x.Group,x.Image,x.StreamUrl,DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()));if(Groups.SelectedItem?.ToString()=="Favorites")Filter();}
protected override void OnKeyDown(System.Windows.Input.KeyEventArgs e){base.OnKeyDown(e);if(e.Key==System.Windows.Input.Key.F&&Items.SelectedItem is XtreamItem x)ToggleFavorite(x);else if(e.Key==System.Windows.Input.Key.Enter&&Items.SelectedItem is XtreamItem y)OpenItem(y);else if(e.Key==System.Windows.Input.Key.Escape)Close();}
void OpenItem(XtreamItem x){if(kind=="series"&&x.StreamUrl is null&&host is not null&&user is not null&&pass is not null)new SeriesWindow(auth,x,host,user,pass).Show();else if(kind=="movie"&&x.StreamUrl is not null&&host is not null&&user is not null&&pass is not null)new MovieDetailsWindow(auth,x,host,user,pass).Show();else if(x.StreamUrl is not null){var q=kind=="live"?((IEnumerable<XtreamItem>)Items.ItemsSource).ToList():new List<XtreamItem>{x};new PlayerWindow(auth,x,q).Show();}}
void Item_DoubleClick(object s,System.Windows.Input.MouseButtonEventArgs e){if(Items.SelectedItem is XtreamItem x)OpenItem(x);}
}