using PlayerOne.Windows.Models;using PlayerOne.Windows.Services;
namespace PlayerOne.Windows;
public partial class InfoWindow:System.Windows.Window{
 readonly DeviceAuth auth;readonly PlayerOneApi api=new();
 public InfoWindow(DeviceAuth a){InitializeComponent();auth=a;Loaded+=LoadAsync;}
 async void LoadAsync(object? sender,System.Windows.RoutedEventArgs e){try{using var d=await api.GetStatusAsync(auth);var x=d.RootElement.TryGetProperty("device",out var z)?z:d.RootElement;var state=x.TryGetProperty("status",out var s)?s.ToString():"unknown";var expiry=x.TryGetProperty("expiresAt",out var ex)?ex.ToString():(x.TryGetProperty("trialExpiresAt",out var tr)?tr.ToString():"—");var plan=x.TryGetProperty("plan",out var pl)?pl.ToString():"—";Status.Text=$"Status: {state}\nActivation duration: {Plan(plan)}";Expiry.Text="Activation expiry: "+Short(expiry);Device.Text=$"Device ID: {auth.DeviceId}\nDevice Key: {auth.DeviceKey}\nDevice type: {DeviceIdentity.Label()}";await LoadSubscriptionAsync();}catch(Exception ex){Status.Text=ex.Message;}}
 async Task LoadSubscriptionAsync(){try{using var d=await api.GetPlaylistsAsync(auth);if(!d.RootElement.TryGetProperty("playlists",out var a))return;var pid=PlaylistSelectionStore.Load();var list=a.EnumerateArray().ToList();var p=pid is null?list.FirstOrDefault():list.FirstOrDefault(x=>x.TryGetProperty("id",out var id)&&id.TryGetInt64(out var n)&&n==pid);if(p.ValueKind!=System.Text.Json.JsonValueKind.Object)return;string V(string n)=>p.TryGetProperty(n,out var v)&&v.ValueKind!=System.Text.Json.JsonValueKind.Null?v.ToString():"—";Subscription.Text=$"Playlist: {V("name")}\nUsername: {V("username")}\nSubscription status: {V("status")}\nServer expiry date: {Short(V("expiresAt"))}";}catch{}}
 static string Plan(string? value)=>value?.ToUpperInvariant() switch{"YEAR"=>"12 months","LIFETIME"=>"Lifetime",_=>string.IsNullOrWhiteSpace(value)?"—":value};
 static string Short(string? value)=>string.IsNullOrWhiteSpace(value)?"—":value.Split('T')[0];
}