using System.Text.Json;using PlayerOne.Windows.Models;using PlayerOne.Windows.Services;
namespace PlayerOne.Windows;
public partial class LiveWindow:System.Windows.Window{
 readonly DeviceAuth auth;readonly PlayerOneApi api=new();List<XtreamItem> all=[];List<XtreamItem> visible=[];
 public sealed record Row(string Number,XtreamItem Item);
 public LiveWindow(DeviceAuth a){InitializeComponent();auth=a;Loaded+=async(_,__)=>await LoadAsync();}
 async Task LoadAsync(){try{using var d=await api.GetPlaylistsAsync(auth);if(!d.RootElement.TryGetProperty("playlists",out var arr)||arr.GetArrayLength()==0)return;var selected=PlaylistSelectionStore.Load();JsonElement p=arr[0];foreach(var x in arr.EnumerateArray())if(x.TryGetProperty("id",out var id)&&id.GetInt64()==selected){p=x;break;}var pid=p.GetProperty("id").GetInt64();PlaylistSelectionStore.Save(pid);using var cfg=await api.GetPlaylistConfigAsync(auth,pid);var q=cfg.RootElement.GetProperty("playlist");var type=q.TryGetProperty("type",out var t)?t.ToString().ToLowerInvariant():"";if(type=="xtream")all=await new XtreamClient().LoadAsync(q.GetProperty("host").ToString(),q.GetProperty("username").ToString(),q.GetProperty("password").ToString(),"live");else if(type=="m3u"&&q.TryGetProperty("url",out var u))all=await new M3uClient().LoadAsync(u.ToString(),"live");Bind();}catch(Exception ex){MessageBox.Show(ex.Message,"Player One");}}
 void Bind(){var gs=all.Select(x=>string.IsNullOrWhiteSpace(x.Group)?"أخرى":x.Group).Distinct(StringComparer.OrdinalIgnoreCase).ToList();Groups.ItemsSource=new[]{"Favorites"}.Concat(gs).Concat(new[]{"All"});Groups.SelectedIndex=Groups.Items.Count-1;Filter();}
 void Filter(){var g=Groups.SelectedItem?.ToString()??"All";var query=SearchBox.Text.Trim();IEnumerable<XtreamItem> src=all;if(query.Length>0)src=all.Where(x=>x.Name.Contains(query,StringComparison.OrdinalIgnoreCase)||x.Group.Contains(query,StringComparison.OrdinalIgnoreCase));else if(g=="Favorites"){var f=PlayerStateStore.Favorites(auth,PlaylistSelectionStore.Load()).Where(x=>x.Type=="live").ToList();src=all.Where(x=>f.Any(v=>v.Id==x.Id||v.StreamUrl==x.StreamUrl));}else if(g!="All")src=all.Where(x=>(string.IsNullOrWhiteSpace(x.Group)?"أخرى":x.Group)==g);visible=src.ToList();Channels.ItemsSource=visible.Select((x,i)=>new Row((i+1).ToString("000"),x)).ToList();CountText.Text=$"{visible.Count} channels";if(Channels.Items.Count>0)Channels.SelectedIndex=0;}
 void Group_Changed(object s,System.Windows.Controls.SelectionChangedEventArgs e)=>Filter();void Search_Changed(object s,System.Windows.Controls.TextChangedEventArgs e)=>Filter();
 void Channel_Changed(object s,System.Windows.Controls.SelectionChangedEventArgs e){if(Channels.SelectedItem is not Row r)return;PreviewName.Text=r.Item.Name;PreviewGroup.Text=r.Item.Group;if(Uri.TryCreate(r.Item.Image,UriKind.Absolute,out var uri))try{PreviewImage.Source=new System.Windows.Media.Imaging.BitmapImage(uri);}catch{}}
 void Play_Click(object s,System.Windows.RoutedEventArgs e)=>Play();void Channel_DoubleClick(object s,System.Windows.Input.MouseButtonEventArgs e)=>Play();
 void Play(){if(Channels.SelectedItem is not Row r||r.Item.StreamUrl is null)return;new PlayerWindow(auth,r.Item,visible).Show();}
 void Favorite_Click(object s,System.Windows.RoutedEventArgs e){if(Channels.SelectedItem is not Row r)return;PlayerStateStore.ToggleFavorite(auth,PlaylistSelectionStore.Load(),new("live",r.Item.Id,r.Item.Name,r.Item.Group,r.Item.Image,r.Item.StreamUrl,DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()));if(Groups.SelectedItem?.ToString()=="Favorites")Filter();}
 void Back_Click(object s,System.Windows.RoutedEventArgs e)=>Close();void Window_KeyDown(object s,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Enter)Play();else if(e.Key==System.Windows.Input.Key.F&&Channels.SelectedItem is Row)Favorite_Click(s,e);else if(e.Key==System.Windows.Input.Key.Escape){Close();e.Handled=true;}}
}