using PlayerOne.Windows.Models;using PlayerOne.Windows.Services;namespace PlayerOne.Windows;
public partial class PlayerWindow:System.Windows.Window{
 readonly DeviceAuth auth;XtreamItem item;readonly List<XtreamItem> queue;int queueIndex;bool paused;int aspect;bool compact;int liveCandidate;List<string> candidates=[];System.Windows.Rect normalBounds;
 public PlayerWindow(DeviceAuth a,XtreamItem i,List<XtreamItem>? q=null){InitializeComponent();auth=a;item=i;queue=q??new(){i};queueIndex=Math.Max(0,queue.FindIndex(x=>x.Id==i.Id));NowPlaying.Text=i.Name;Loaded+=(_,__)=>Play();Closing+=(_,__)=>Save();}
 void Play(){if(item.StreamUrl is null)return;candidates=(item.Kind=="live"?LivePlayback.Candidates(item.StreamUrl):new[]{item.StreamUrl}).Distinct().ToList();liveCandidate=0;PlayCandidate();}void PlayCandidate(){if(liveCandidate>=candidates.Count){PlayerStatus.Text="Playback failed";return;}Media.Source=new Uri(candidates[liveCandidate]);PlayerStatus.Text="Loading…";Media.Play();}
 void Pause_Click(object s,System.Windows.RoutedEventArgs e){if(paused)Media.Play();else Media.Pause();paused=!paused;}
 void Aspect_Click(object s,System.Windows.RoutedEventArgs e){aspect=(aspect+1)%3;Media.Stretch=aspect switch{0=>System.Windows.Media.Stretch.UniformToFill,1=>System.Windows.Media.Stretch.Uniform,_=>System.Windows.Media.Stretch.Fill};}
 void Compact_Click(object s,System.Windows.RoutedEventArgs e)=>ToggleCompact();void Full_Click(object s,System.Windows.RoutedEventArgs e)=>ToggleFull();
 void ToggleFull(){if(WindowStyle==System.Windows.WindowStyle.None){WindowStyle=System.Windows.WindowStyle.SingleBorderWindow;WindowState=System.Windows.WindowState.Normal;}else{WindowStyle=System.Windows.WindowStyle.None;WindowState=System.Windows.WindowState.Maximized;}}
 void ToggleCompact(){if(!compact){normalBounds=new System.Windows.Rect(Left,Top,Width,Height);Width=430;Height=250;Topmost=true;ResizeMode=System.Windows.ResizeMode.CanResize;Left=SystemParameters.WorkArea.Right-Width-18;Top=SystemParameters.WorkArea.Bottom-Height-18;}else{Topmost=false;Left=normalBounds.Left;Top=normalBounds.Top;Width=normalBounds.Width;Height=normalBounds.Height;}compact=!compact;}
 void Window_KeyDown(object s,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Escape&&WindowStyle==System.Windows.WindowStyle.None)ToggleFull();else if(e.Key==System.Windows.Input.Key.Space)Pause_Click(s,e);else if(e.Key==System.Windows.Input.Key.F11)ToggleFull();else if(e.Key==System.Windows.Input.Key.P)ToggleCompact();else if(e.Key==System.Windows.Input.Key.Left)Media.Position=Media.Position-TimeSpan.FromSeconds(10);else if(e.Key==System.Windows.Input.Key.Right)Media.Position=Media.Position+TimeSpan.FromSeconds(10);}
 void Media_Failed(object s,System.Windows.ExceptionRoutedEventArgs e){if(item.Kind=="live"&&PlayerSettings.Load().AutoReconnect&&++liveCandidate<candidates.Count){PlayCandidate();return;}PlayerStatus.Text=e.ErrorException?.Message??"Playback error";}\n void Media_Opened(object s,System.Windows.RoutedEventArgs e){PlayerStatus.Text="";var r=PlayerStateStore.Recents(auth,PlaylistSelectionStore.Load()).FirstOrDefault(x=>x.StreamUrl==item.StreamUrl&&PlayerStateStore.Meaningful(x));if(r is not null&&item.Kind!="live")Media.Position=TimeSpan.FromMilliseconds(r.PositionMs);}
 void Media_Ended(object s,System.Windows.RoutedEventArgs e){Save();if(item.Kind=="series"&&AdvancedSettings.Load().AutoNext&&queueIndex+1<queue.Count){item=queue[++queueIndex];NowPlaying.Text=item.Name;Play();}}
 void Save(){if(item.Kind=="live")return;long dur=Media.NaturalDuration.HasTimeSpan?(long)Media.NaturalDuration.TimeSpan.TotalMilliseconds:0;long pos=(long)Media.Position.TotalMilliseconds;PlayerStateStore.AddRecent(auth,PlaylistSelectionStore.Load(),new(item.Kind,item.Name,item.Group,item.Image,item.StreamUrl,pos,dur,DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()));}
}