using LibVLCSharp.Shared;using PlayerOne.Windows.Models;using PlayerOne.Windows.Services;namespace PlayerOne.Windows;
public partial class PlayerWindow:System.Windows.Window{
 readonly DeviceAuth auth;XtreamItem item;readonly List<XtreamItem> queue;int queueIndex;readonly LibVLC lib;readonly MediaPlayer mp;Media? media;bool compact;int aspect;int liveCandidate;List<string> candidates=[];Rect normalBounds;
 public PlayerWindow(DeviceAuth a,XtreamItem i,List<XtreamItem>? q=null){InitializeComponent();Core.Initialize();auth=a;item=i;queue=q??new(){i};queueIndex=Math.Max(0,queue.FindIndex(x=>x.Id==i.Id));lib=new LibVLC("--network-caching=1200","--file-caching=800","--no-video-title-show");mp=new MediaPlayer(lib);VideoView.MediaPlayer=mp;mp.Playing+=(_,__)=>Dispatcher.Invoke(OnPlaying);mp.EndReached+=(_,__)=>Dispatcher.Invoke(OnEnded);mp.EncounteredError+=(_,__)=>Dispatcher.Invoke(OnError);NowPlaying.Text=i.Name;Loaded+=(_,__)=>Play();Closing+=(_,__)=>{Save();mp.Stop();media?.Dispose();mp.Dispose();lib.Dispose();};}
 void Play(){if(string.IsNullOrWhiteSpace(item.StreamUrl))return;candidates=(item.Kind=="live"?LivePlayback.Candidates(item.StreamUrl):new[]{item.StreamUrl}).Distinct().ToList();liveCandidate=0;PlayCandidate();}
 void PlayCandidate(){if(liveCandidate>=candidates.Count){PlayerStatus.Text="Playback failed";return;}media?.Dispose();media=new Media(lib,new Uri(candidates[liveCandidate]));PlayerStatus.Text="Loading…";mp.Play(media);}
 void OnPlaying(){PlayerStatus.Text="";if(item.Kind!="live"){var r=PlayerStateStore.Recents(auth,PlaylistSelectionStore.Load()).FirstOrDefault(x=>x.StreamUrl==item.StreamUrl&&PlayerStateStore.Meaningful(x));if(r is not null&&r.PositionMs>0&&mp.Time<3000)mp.Time=r.PositionMs;}}
 void OnError(){if(item.Kind=="live"&&PlayerSettings.Load().AutoReconnect&&++liveCandidate<candidates.Count){PlayCandidate();return;}PlayerStatus.Text="Playback error";}
 void OnEnded(){Save();if(item.Kind=="series"&&AdvancedSettings.Load().AutoNext&&queueIndex+1<queue.Count){item=queue[++queueIndex];NowPlaying.Text=item.Name;Play();}}
 void Pause_Click(object s,RoutedEventArgs e){if(mp.IsPlaying)mp.Pause();else mp.Play();}
 void Back_Click(object s,RoutedEventArgs e)=>Seek(-10000);void Forward_Click(object s,RoutedEventArgs e)=>Seek(10000);void Seek(long d){if(item.Kind!="live"&&mp.Length>0)mp.Time=Math.Clamp(mp.Time+d,0,mp.Length);}
 void Aspect_Click(object s,RoutedEventArgs e){aspect=(aspect+1)%3;mp.AspectRatio=aspect switch{0=>null,1=>"16:9",_=>"4:3"};PlayerStatus.Text=aspect switch{0=>"Auto aspect",1=>"16:9",_=>"4:3"};}
 void Compact_Click(object s,RoutedEventArgs e)=>ToggleCompact();void Full_Click(object s,RoutedEventArgs e)=>ToggleFull();
 void ToggleFull(){if(WindowStyle==WindowStyle.None){WindowStyle=WindowStyle.SingleBorderWindow;WindowState=WindowState.Normal;}else{WindowStyle=WindowStyle.None;WindowState=WindowState.Maximized;}}
 void ToggleCompact(){if(!compact){normalBounds=new Rect(Left,Top,Width,Height);Width=430;Height=250;Topmost=true;Left=SystemParameters.WorkArea.Right-Width-18;Top=SystemParameters.WorkArea.Bottom-Height-18;}else{Topmost=false;Left=normalBounds.Left;Top=normalBounds.Top;Width=normalBounds.Width;Height=normalBounds.Height;}compact=!compact;}
 void Window_KeyDown(object s,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Escape&&WindowStyle==WindowStyle.None)ToggleFull();else if(e.Key==System.Windows.Input.Key.Space)Pause_Click(s,e);else if(e.Key==System.Windows.Input.Key.F11)ToggleFull();else if(e.Key==System.Windows.Input.Key.P)ToggleCompact();else if(e.Key==System.Windows.Input.Key.Left)Seek(-10000);else if(e.Key==System.Windows.Input.Key.Right)Seek(10000);else if(item.Kind=="live"&&e.Key==System.Windows.Input.Key.Down)SwitchLive(1);else if(item.Kind=="live"&&e.Key==System.Windows.Input.Key.Up)SwitchLive(-1);else if(e.Key==System.Windows.Input.Key.Escape)Close();}
 void SwitchLive(int delta){if(queue.Count<2)return;Save();queueIndex=(queueIndex+delta+queue.Count)%queue.Count;item=queue[queueIndex];NowPlaying.Text=item.Name;Play();}
 void Save(){if(item.Kind=="live"||string.IsNullOrWhiteSpace(item.StreamUrl))return;PlayerStateStore.AddRecent(auth,PlaylistSelectionStore.Load(),new(item.Kind,item.Name,item.Group,item.Image,item.StreamUrl,Math.Max(0,mp.Time),Math.Max(0,mp.Length),DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()));}
}