using System.Text.Json;using PlayerOne.Windows.Models;using PlayerOne.Windows.Services;namespace PlayerOne.Windows;
public partial class PlaylistWindow:System.Windows.Window{readonly DeviceAuth auth;readonly PlayerOneApi api=new();public PlaylistWindow(DeviceAuth a){InitializeComponent();auth=a;Loaded+=async(_,__)=>await LoadAsync();}
void Back_Click(object s,RoutedEventArgs e)=>Close();
async Task LoadAsync(){try{using var d=await api.GetPlaylistsAsync(auth);var x=new List<DevicePlaylist>();if(d.RootElement.TryGetProperty("playlists",out var a))foreach(var p in a.EnumerateArray())x.Add(new(p.GetProperty("id").GetInt64(),p.TryGetProperty("name",out var n)?n.ToString():"Playlist",p.TryGetProperty("type",out var t)?t.ToString():"playlist",null,null));List.ItemsSource=x;}catch(Exception ex){MessageBox.Show(ex.Message,"Player One");}}
void Select_Click(object s,RoutedEventArgs e){if(List.SelectedItem is DevicePlaylist p){PlaylistSelectionStore.Save(p.Id);DialogResult=true;}}
async void Refresh_Click(object s,RoutedEventArgs e)=>await LoadAsync();
async void AddM3u_Click(object s,RoutedEventArgs e){var d=new PlaylistEditDialog("M3U"){Owner=this};if(d.ShowDialog()==true){var id=await api.AddM3uAsync(auth,d.PlaylistName,d.Url);PlaylistSelectionStore.Save(id);await LoadAsync();}}
async void AddXtream_Click(object s,RoutedEventArgs e){var d=new PlaylistEditDialog("Xtream"){Owner=this};if(d.ShowDialog()==true){var id=await api.AddXtreamAsync(auth,d.PlaylistName,d.Host,d.Username,d.Password);PlaylistSelectionStore.Save(id);await LoadAsync();}}
async void Code_Click(object s,RoutedEventArgs e){var d=new ProviderLoginDialog{Owner=this};if(d.ShowDialog()==true){using var _=await api.ProviderLoginAsync(auth,d.Code,d.Username,d.Password);await LoadAsync();}}
async void Edit_Click(object s,RoutedEventArgs e){if(List.SelectedItem is not DevicePlaylist p)return;try{using var cfg=await api.GetPlaylistConfigAsync(auth,p.Id);var q=cfg.RootElement.GetProperty("playlist");var type=q.TryGetProperty("type",out var t)?t.ToString().ToLowerInvariant():p.Type.ToLowerInvariant();var d=new PlaylistEditDialog(type=="m3u"?"M3U":"Xtream"){Owner=this};if(type=="m3u"){d.SetM3u(p.Name,q.TryGetProperty("url",out var u)?u.ToString():"");if(d.ShowDialog()==true)await api.UpdateM3uAsync(auth,p.Id,d.PlaylistName,d.Url);}else{d.SetXtream(p.Name,q.TryGetProperty("host",out var h)?h.ToString():"",q.TryGetProperty("username",out var un)?un.ToString():"",q.TryGetProperty("password",out var pw)?pw.ToString():"");if(d.ShowDialog()==true)await api.UpdateXtreamAsync(auth,p.Id,d.PlaylistName,d.Host,d.Username,d.Password);}await LoadAsync();}catch(Exception ex){MessageBox.Show(ex.Message,"Player One");}}
async void Delete_Click(object s,RoutedEventArgs e){if(List.SelectedItem is DevicePlaylist p&&MessageBox.Show($"Delete {p.Name}?","Player One",MessageBoxButton.YesNo)==MessageBoxResult.Yes){await api.DeletePlaylistAsync(auth,p.Id);var deleted=p.Id;await LoadAsync();if(PlaylistSelectionStore.Load()==deleted&&List.Items.Count>0&&List.Items[0] is DevicePlaylist first)PlaylistSelectionStore.Save(first.Id);}}
}