using LibVLCSharp.Shared;using PlayerOne.Windows.Models;using PlayerOne.Windows.Services;namespace PlayerOne.Windows;
public partial class PlayerWindow:System.Windows.Window{
 readonly DeviceAuth auth;XtreamItem item;readonly List<XtreamItem> queue;int queueIndex;readonly LibVLC lib;readonly MediaPlayer mp;Media? media;bool compact;int aspect;int liveCandidate;int reconnectAttempts;List<string> candidates=[];Rect normalBounds;
 public PlayerWindow(DeviceAuth a,XtreamItem i,List<XtreamItem>? q=null){InitializeComponent();Core.Initialize();auth=a;item=i;queue=q??new(){i};queueIndex=Math.Max(0,queue.FindIndex(x=>x.Id==i.Id));var adv=AdvancedSettings.Load();var cache=adv.BufferProfile switch{"fast"=>"650","stable"=>"2200",_=>"1200"};lib=new LibVLC("--network-caching="+cache,"--file-caching="+cache,"--no-video-title-show");mp=new MediaPlayer(lib);VideoView.MediaPlayer=mp;mp.Playing+=(_,__)=>Dispatcher.Invoke(OnPlaying);mp.EndReached+=(_,__)=>Dispatcher.Invoke(OnEnded);mp.EncounteredError+=(_,__)=>Dispatcher.Invoke(OnError);NowPlaying.Text=i.Name;NowGroup.Text=i.Group;Loaded+=(_,__)=>{ApplySettings();FavoriteButton.Visibility=item.Kind=="live"?Visibility.Visible:Visibility.Collapsed;PrevButton.Visibility=item.Kind=="live"?Visibility.Visible:Visibility.Collapsed;NextButton.Visibility=item.Kind=="live"?Visibility.Visible:Visibility.Collapsed;if(item.Kind=="live")FavoriteButton.Content=PlayerStateStore.IsFavorite(auth,PlaylistSelectionStore.Load(),"live",item.Id)?"♥":"♡";Play();};Closing+=(_,__)=>{Save();mp.Stop();media?.Dispose();mp.Dispose();lib.Dispose();};}
 void Play(){if(string.IsNullOrWhiteSpace(item.StreamUrl))return;var adv=AdvancedSettings.Load();candidates=(item.Kind=="live"?LivePlayback.Candidates(item.StreamUrl):new[]{item.StreamUrl}).Distinct().ToList();if(item.Kind=="live"&&adv.StreamingFormat!="auto"){var wanted=adv.StreamingFormat=="hls"?".m3u8":".ts";candidates=candidates.OrderByDescending(x=>x.Contains(wanted,StringComparison.OrdinalIgnoreCase)).ToList();}liveCandidate=0;PlayCandidate();}
 void PlayCandidate(){if(liveCandidate>=candidates.Count){PlayerStatus.Text="Playback failed";return;}media?.Dispose();media=new Media(lib,new Uri(candidates[liveCandidate]));PlayerStatus.Text="Loading…";mp.Play(media);}
 void OnPlaying(){PlayerStatus.Text="";reconnectAttempts=0;if(item.Kind=="live")PlayerStateStore.AddRecent(auth,PlaylistSelectionStore.Load(),new("live",item.Name,item.Group,item.Image,item.StreamUrl,0,0,DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()));if(item.Kind!="live"){var r=PlayerStateStore.Recents(auth,PlaylistSelectionStore.Load()).FirstOrDefault(x=>x.StreamUrl==item.StreamUrl&&PlayerStateStore.Meaningful(x));if(r is not null&&r.PositionMs>0&&mp.Time<3000)mp.Time=r.PositionMs;}}
 async void OnError(){if(item.Kind=="live"&&PlayerSettings.Load().AutoReconnect){if(++liveCandidate<candidates.Count){await Task.Delay(900);PlayCandidate();return;}if(reconnectAttempts<2){reconnectAttempts++;await Task.Delay(900*reconnectAttempts);liveCandidate=0;PlayCandidate();return;}}PlayerStatus.Text="Playback error";}
 void OnEnded(){Save();if(item.Kind=="series"&&AdvancedSettings.Load().AutoNext&&queueIndex+1<queue.Count){item=queue[++queueIndex];NowPlaying.Text=item.Name;NowGroup.Text=item.Group;Play();}}
 void ApplySettings(){var s=PlayerSettings.Load();mp.AspectRatio=s.DefaultAspect switch{"fill"=>"16:9","zoom"=>"4:3",_=>null};}
 void CycleAudio(){var tracks=mp.AudioTrackDescription?.ToList();if(tracks is null||tracks.Count<2){PlayerStatus.Text="No alternate audio track";return;}var ids=tracks.Select(x=>x.Id).ToList();var i=ids.IndexOf(mp.AudioTrack);mp.SetAudioTrack(ids[(i+1+ids.Count)%ids.Count]);PlayerStatus.Text="Audio track changed";}
 void CycleSubtitle(){var s=PlayerSettings.Load();if(!s.SubtitlesEnabled){mp.SetSpu(-1);PlayerStatus.Text="Subtitles off";return;}var tracks=mp.SpuDescription?.ToList();if(tracks is null||tracks.Count==0){PlayerStatus.Text="No subtitles";return;}var ids=tracks.Select(x=>x.Id).ToList();var i=ids.IndexOf(mp.Spu);mp.SetSpu(ids[(i+1+ids.Count)%ids.Count]);PlayerStatus.Text="Subtitle track changed";}
 void Prev_Click(object s,RoutedEventArgs e){if(item.Kind=="live")SwitchLive(-1);} void Next_Click(object s,RoutedEventArgs e){if(item.Kind=="live")SwitchLive(1);} void Favorite_Click(object s,RoutedEventArgs e){if(item.Kind=="live")ToggleLiveFavorite();} void Pause_Click(object s,RoutedEventArgs e){if(mp.IsPlaying)mp.Pause();else mp.Play();}
 void Back_Click(object s,RoutedEventArgs e)=>Seek(-10000);void Forward_Click(object s,RoutedEventArgs e)=>Seek(10000);void Seek(long d){if(item.Kind!="live"&&mp.Length>0)mp.Time=Math.Clamp(mp.Time+d,0,mp.Length);}
 void Audio_Click(object s,RoutedEventArgs e)=>CycleAudio();void Subs_Click(object s,RoutedEventArgs e)=>CycleSubtitle();
 void Aspect_Click(object s,RoutedEventArgs e){aspect=(aspect+1)%3;mp.AspectRatio=aspect switch{0=>null,1=>"16:9",_=>"4:3"};PlayerStatus.Text=aspect switch{0=>"Auto aspect",1=>"16:9",_=>"4:3"};}
 void Compact_Click(object s,RoutedEventArgs e)=>ToggleCompact();void Full_Click(object s,RoutedEventArgs e)=>ToggleFull();
 void ToggleFull(){if(WindowStyle==WindowStyle.None){WindowStyle=WindowStyle.SingleBorderWindow;WindowState=WindowState.Normal;}else{WindowStyle=WindowStyle.None;WindowState=WindowState.Maximized;}}
 void ToggleCompact(){if(!compact){normalBounds=new Rect(Left,Top,Width,Height);Width=430;Height=250;Topmost=true;Left=SystemParameters.WorkArea.Right-Width-18;Top=SystemParameters.WorkArea.Bottom-Height-18;}else{Topmost=false;Left=normalBounds.Left;Top=normalBounds.Top;Width=normalBounds.Width;Height=normalBounds.Height;}compact=!compact;}
 void Window_KeyDown(object s,System.Windows.Input.KeyEventArgs e){if(e.Key==System.Windows.Input.Key.Escape&&WindowStyle==WindowStyle.None)ToggleFull();else if(e.Key==System.Windows.Input.Key.Space)Pause_Click(s,e);else if(e.Key==System.Windows.Input.Key.F11)ToggleFull();else if(e.Key==System.Windows.Input.Key.P)ToggleCompact();else if(e.Key==System.Windows.Input.Key.A)CycleAudio();else if(e.Key==System.Windows.Input.Key.S)CycleSubtitle();else if(e.Key==System.Windows.Input.Key.Left)Seek(-10000);else if(e.Key==System.Windows.Input.Key.Right)Seek(10000);else if(item.Kind=="live"&&e.Key==System.Windows.Input.Key.Down)SwitchLive(1);else if(item.Kind=="live"&&e.Key==System.Windows.Input.Key.Up)SwitchLive(-1);else if(item.Kind=="live"&&e.Key==System.Windows.Input.Key.F)ToggleLiveFavorite();else if(e.Key==System.Windows.Input.Key.Escape)Close();}
 void ToggleLiveFavorite(){var on=PlayerStateStore.ToggleFavorite(auth,PlaylistSelectionStore.Load(),new("live",item.Id,item.Name,item.Group,item.Image,item.StreamUrl,DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()));FavoriteButton.Content=on?"♥":"♡";PlayerStatus.Text=on?"Added to favorites":"Removed from favorites";}
 void SwitchLive(int delta){if(queue.Count<2)return;Save();queueIndex=(queueIndex+delta+queue.Count)%queue.Count;item=queue[queueIndex];NowPlaying.Text=item.Name;NowGroup.Text=item.Group;FavoriteButton.Content=PlayerStateStore.IsFavorite(auth,PlaylistSelectionStore.Load(),"live",item.Id)?"♥":"♡";Play();}
 void Save(){if(item.Kind=="live"||string.IsNullOrWhiteSpace(item.StreamUrl))return;PlayerStateStore.AddRecent(auth,PlaylistSelectionStore.Load(),new(item.Kind,item.Name,item.Group,item.Image,item.StreamUrl,Math.Max(0,mp.Time),Math.Max(0,mp.Length),DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()));}
}